  module.exports = {
    'Super Admin': {
      canViewBookings: true,
      canManageBookings: true,
      canManageServices: true,
      canManageCustomers: true,
      canManageAdmins: true,
      canViewReports: true,
      canManageSettings: true,
      canManageGallery: true,
      canManageReviews: true,
      canManageTeam: true,
      canManagePromotionBookings: true,
    },
    Manager: {
      canViewBookings: true,
      canManageBookings: true,
      canManageServices: true,
      canManageCustomers: true,
      canManageAdmins: false,
      canViewReports: true,
      canManageSettings: false,
      canManageGallery: true,
      canManageReviews: true,
      canManageTeam: false,
      canManagePromotionBookings: true,
    },
    Staff: {
      canViewBookings: true,
      canManageBookings: true,
      canManageServices: false,
      canManageCustomers: false,
      canManageAdmins: false,
      canViewReports: false,
      canManageSettings: false,
      canManageGallery: false,
      canManageReviews: false,
      canManageTeam: false,
      canManagePromotionBookings: false,
    }
  };